apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.name }}
  labels:
    app: {{ $.Values.name }}
spec:
  replicas: {{ $.Values.podReplicas }}
  selector:
    matchLabels:
      app: {{ $.Values.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.name }}
    spec:
      containers:
      - name: {{ $.Values.name }}
        image: {{ $.Values.deployment.image }}:{{ $.Values.deployment.tag }}
        ports:
        - containerPort: {{ $.Values.containerPort }}