apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: avl-ingress
  namespace: avl-namespace
spec:
  rules:
  - host: avl-tehnicki-zadatak.com
    http:
      paths:
      - defaultBackend:
          service:
            name: avl-client-service
          service:
            port: 80