apiVersion: v1
kind: ConfigMap
metadata:
  name: client-service-config
data:
  config.json: |
    {
    	"clientApi":"http://avl-client-service/hash",
    	"backendApi":"http://avl-backend-service/"
    }