apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: avl-ingress
  namespace: avl-namespace
spec:
  rules:
  - host: avl-tehnicki-zadatak.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: avl-client-service
            port:
              number: 80