version: "3.7"
services:
  avl_backend:
    container_name: avl-backend-api
    image: avl_backend:latest
    build:
        context: .
        dockerfile: ./avl_backend/Dockerfile
    ports:
      - 5020:5020
  avl_client:
    container_name: avl-client-api
    image: avl_client:latest
    build:
        context: .
        dockerfile: ./avl_client/Dockerfile
    ports:
      - 5010:5010