name: 'TPT Home finder and runner'
description: 'Find TPT home and run tpt.exe'
inputs:
  tptFileName:
    description: 'tpt file name'
    required: true
  tptFilePath:
    description: 'tpt file path'
    required: true
  tptFileNoExtension:
    description: 'tpt file extension'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install TestRunner and update config
      run: |
        echo 'Execute update_config.py'
        echo ${{ env.tpt_file_path }}
      shell: powershell
      env:
        tpt_file_path: ${{ inputs.tptFilePath }}\${{ inputs.tptFileNoExtension }}\${{ inputs.tptFileName }}