apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.configmap.name }}
  namespace: {{ $.Values.namespace }}
data:
  config.json: |
    {
    	"clientApi":"http://avl-client-service",
    	"backendApi":"http://avl-backend-service"
    }