apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $.Values.name }}
spec:
  replicas: {{ $.Values.deployment.podReplicas }}
  selector:
    matchLabels:
      app: {{ $.Values.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.name }}
    spec:
      containers:
      - name: {{ $.Values.name }}
        image: {{ $.Values.deployment.image }}:{{ $.Values.deployment.tag }}
        ports:
        - containerPort: {{ $.Values.deployment.containerPort }}
        volumeMounts:
        - name: {{ $.Values.deployment.configVolumeLabel }}
          mountPath: {{ $.Values.deployment.voulmePath }}
      volumes:
      - name: {{ $.Values.deployment.configVolumeLabel }}
        configMap:
          name: {{ $.Values.configmap.name }}